### PR TITLE
Update to GitHub Workflow + Badges

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] add GitHub workflow for #34
+ [x] update CI/build badge
+ [x] update Hits badge to use `.com`

### CODE REVIEW

**Comment by nelsonic** [comment]
Annoyingly, for Node.js projects, we are forced to upload the `package-lock.json` file (_super noisy_) to GitHub:
https://github.com/dwyl/javascript-todo-list-tutorial/runs/4094346133?check_suite_focus=true#step:3:11
image

**Comment by nelsonic** [comment]
Done. ✅ 
[GitHub Workflow Status](https://github.com/dwyl/javascript-todo-list-tutorial/actions)
[codecov.io](http://codecov.io/github/dwyl/javascript-todo-list-tutorial?branch=master)
[Dependencies: None](https://github.com/dwyl/javascript-todo-list-tutorial/blob/master/package.json#L12 "Zero Dependencies")
[contributions welcome](https://github.com/dwyl/javascript-todo-list-tutorial/issues)
[HitCount](http://hits.dwyl.com/dwyl/javascript-todo-list-tutorial)

**Comment by nelsonic** [comment]
@SimonLab hopefully this update is self-explanatory. Thanks for review+merge. 👍

**Review by SimonLab — APPROVED** [review]
Looks good :+1:

**Pull request merged**
